### ISSUE TITLE
Try to eliminate useNetworkGateway settings

### ISSUE THREAD

**Issue by augi** [avast/docker-compose-gradle-plugin#19]
Now, if someone uses Docker for Mac then they must manually set `useNetworkGateway=false`. It would be great to automatically detect presence of Docker for Mac and if present then automatically use `localhost`.

**Comment by augi** [comment]
Could you please look at this, @remen?

**Comment by augi** [comment]
Also discussed in #18. We should probably wait for final version of Docker for Mac/Windows.

**Comment by remen** [comment]
Well, after thinking about it for 5m, I think a good temporary workaround would be to determine whether it is a Mac at all, in which case either DOCKER_HOST will be set (if using docker-machine), or we can assume that we can connect to localhost.

The situation is probably a bit more complex than that, because Docker for Mac has a bunch of options for networking. But this would at least support the majority of the use cases, and we can evolve the design from there.

Sound good? In that case I'll investigate this path and send another PR.

**Comment by augi** [comment]
Sounds good, thanks!

**Comment by remen** [comment]
Alrighty. Added a new PR which checks whether running on Mac.

If this is merged, when is the next release upcoming? Need to know whether to release an internal version at our company or if we can wait for next release of this plugin.

**Comment by augi** [comment]
I will release a new version right after merging.
