### ISSUE TITLE
Support for scale 

### ISSUE THREAD

**Issue by s4s0l** [avast/docker-compose-gradle-plugin#37]
Hi, what about adding support for docker-compose scale?

docker-compose people are working on some changes in this matter ( https://github.com/docker/compose/issues/1661) but until they get it sorted out it would be nice not having to hardcode execs it in gradle...

**Comment by augi** [comment]
Hi, the scaling support would actually lead to massive changes in the plugin as the plugin now supposes that there is only one instance of each service.

I would personally prefer to wait for the implementation in docker-compose and redesign the plugin afterward. But if you want to prepare the PR then I will happily accept it.

Thanks!

**Comment by augi** [comment]
Do you any idea how the API of this plugin should look like?

**Comment by andrcuns** [comment]
Hi,
Any plans on implementing --scale option now that it is added in 1.13 of docker-compose?

**Comment by augi** [comment]
I don't need it in my projects so I'm not going to implement this feature. What is your use-case, please? Anyway, feel free to prepare PR.

**Comment by andrcuns** [comment]
We are setting up selenium grid with multiple nodes, depending in how many parallel flows will run our tests. For a while I had to use a custom gradle task that runs docker-compose scale command, but --scale option would be immensely more useful and less complicated, since health check would then also be performed which isn't my my case.
I will maybe try to look in to that myself, though I have very little experience in this kind of development, more of a test engineer then developer :D

**Comment by augi** [comment]
Released as `0.4.0`.
