### ISSUE TITLE
Possible to pull docker container from private registry?

### ISSUE THREAD

**Issue by golauty** [avast/docker-compose-gradle-plugin#50]
Hi,
I get following issue when i try to pull a docker container from a private registry  in hub.docker.com:
`Pulling repository docker.io/someprivateRepo/someImage
 Error: image someprivateRepo/someImage:latest not found`

When i try that with `docker pull` command i have no issues.

So my question is there a restriction? Can i do that?

**Comment by augi** [comment]
Hi,

what version of docker-compose do you use? There was a bug in Docker Compose that was fixed in [1.8.1](https://github.com/docker/compose/releases/tag/1.8.1) (see the first bug fixes).

The problem was that Docker started to use a new way how to store credentials but this change wasn't reflected in Docker Compose.

To explain it - Docker Compose doesn't use Docker CLI under the hood - it communicates with Docker daemon via REST API instead. So they had to "reimplement" the support for new credentials store in Python.
