### ISSUE TITLE
ServiceInfos expect container name with specific format.

### ISSUE THREAD

**Issue by tabiul** [avast/docker-compose-gradle-plugin#81]
If I add `container_name` as part of my `docker-compose.yml` file then I am not able to call `dockerCompose.servicesInfos.<service_name>.'<container_name>'`. Looking at the code, the reason is due to [this](https://github.com/avast/docker-compose-gradle-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeUp.groovy#L124). In case the `container_name` is set then the pattern does not match. Is there a need for the pattern check ? Maybe I am missing something, is there anything wrong if we just use the value of `inspection.Name` excluding the `/` ?

**Comment by andrcuns** [comment]
By default, container name is constructed from projectName and Container name, so it adds some complexity on querying service infos, You kind of have to take in to account what the full name will look like. In tests it would be something ugly like `gradle5729327650986943343projectdir`, there fore it was decided to omit using the full container name.
Also with container_name variable, it's a bit tricky because it wouldn't be compatible with scale option for example, so that would most have to be handled as well.
Not sure what @augi thinks about this, but in automated testing scenarios, I don't see much benefit from using specific container_name variable.

**Comment by augi** [comment]
Exactly - having hard-coded container name doesn't make sense in automated testing scenarios because it could easily collide on integration server etc.

Anyway, it would be nice to support also your use-case. I will look at it how complicated it would be.

E.g. we could check in the YAML file if `container_name` is specified.

**Comment by tabiul** [comment]
Thanks @augi

**Comment by augi** [comment]
Released as 0.4.3.
