### ISSUE TITLE
Remove running containers for a failed task

### ISSUE THREAD

**Issue by erasmas** [avast/docker-compose-gradle-plugin#84]
Hi! Thanks for all the great work on this plugin, it's the best one I could find for Gradle.

I'm having one issue with it though. I'm not very familiar with Gradle so maybe I missed something here. I'm trying to stop Docker containers in case `integrationTest` task failed.

```
task integrationTest(type: Test) {
    dependsOn composeUp, intTest
    finalizedBy composeDown
}

dockerCompose {
    stopContainers = true
}
```

With this setup, even if some test failed I see that `composeDown` is not executed which leaves Docker containers running. Is there a way to stop them regardless of the task result? Thanks!

**Comment by augi** [comment]
Hi! The behavior you are describing is very strange because `finalizedBy` is exactly what you want - it executes the `composeDown` even if `integrationTest` fails.

Are you sure that the failing task is really `integrationTest`? Isn't it `intTest`?

Try to execute your project with `--info` or `--debug` to get more info about the issue. Thanks!

**Comment by erasmas** [comment]
`intTest` is the task that actually executes integration tests. This task is added by `org.unbroken-dome.test-sets` plugin. `integrationTest` is wrapper task that depends on `composeDown` and starts `intTest` task.

**Comment by augi** [comment]
I think that this happens in your Gradle script:
1. You execute something like `./gradlew integrationTest`
2. Gradle executes all the dependencies of `integrationTest`, so `composeUp` and then `intTest`.
3. `intTest` fails and so the build is interrupted. The `integrationTest` has NOT been executed yet (because one of dependency, `intTest`, failed) and so `composeDown` is not executed even in case of failure.

If you don't need the wrapper task then you can use this:
```gradle
intTest.dependsOn composeUp
intTest.finalizedBy composeDown
```
OR this shorthand: `dockerCompose.isRequiredBy(intTest)`

If you need the wrapper task then you could use this:
```gradle
dockerCompose.isRequiredBy(intTest)
task integrationTest(type: Test) {
    dependsOn intTest
}
```
